{% set name = "matrix-py3" %}
{% set version = "0.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/matrix-py3-{{ version }}.tar.gz
  sha256: 56d10cce66a7e0277347e8252b7767efb1fe0b23c55ed5b15a3163cd88f0d80b

build:
  number: 1
  noarch: python
  entry_points:
    - matrix = matrix3:matrix_cmd
    - coolmatrix = matrix3:cool_matrix_cmd
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pebble

test:
  imports:
    - matrix3
  commands:
    - pip check
    - matrix --help
    - coolmatrix --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/chunribu/matrix-py3
  summary: Python3 implementation of cmatrix with a timer
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chunribu
